### PR TITLE
fix mrc import axes

### PR DESCRIPTION
**Pull request by martinschorb**
tests are fine wrt axis mess because we use the same library for writing and reading the files.

### CODE REVIEW

**Comment by martinschorb** [comment]
For me, locally the tests went through. So I didn't check that particular one. I'll have a look. I suspect the indeces with the swapped axes might cause it to fail.

**Comment by constantinpape** [comment]
> For me, locally the tests went through. So I didn't check that particular one. I'll have a look. I suspect the indeces with the swapped axes might cause it to fail.

Do you have `mrcfile` installed in the environment where you run the tests? Without it the tests are just being skipped (because I don't want to add it as a hard dependency since for me this is a legacy file format...)

**Comment by martinschorb** [comment]
> Do you have `mrcfile` installed in the environment where you run the tests? Without it the tests are just being skipped (because I don't want to add it as a hard dependency since for me this is a legacy file format...)

Yes, I have it. But it could be that I had some array left in memory when checking or alternatively forgot to manually call that particular test function. I am not very familiar with the `unittest` classes as I usually use `pytest`, but I'll give it a try.

**Comment by constantinpape** [comment]
> Yes, I have it. But it could be that I had some array left in memory when checking or alternatively forgot to manually call that particular test function. I am not very familiar with the `unittest` classes as I usually use `pytest`, but I'll give it a try.

Just do `python test_mrc_wrapper.py` and it will run all tests in the file.

**Comment by martinschorb** [comment]
> Just do `python test_mrc_wrapper.py` and it will run all tests in the file.

Yes, that's what I did and it went through. Otherwise I wouldn't have filed the PR. Strange...

**Comment by constantinpape** [comment]
FWIW I just tried locally and the tests also fail for me.
I am using python 3.9 with the following mrcfile:
```
mrcfile                   1.3.0              pyh44b312d_0    conda-forge
```

**Comment by martinschorb** [comment]
It seems we haven't included the axis juggling...? that would explain https://github.com/mobie/clem-example-project/issues/20

**Comment by martinschorb** [comment]
???
```
$ python io_tests/test_mrc_wrapper.py 
....
----------------------------------------------------------------------
Ran 4 tests in 0.497s

OK
```
with:
```
$ python -c 'import mrcfile; print(mrcfile.version.__version__)'
1.3.0
```

**Comment by constantinpape** [comment]
> ???
> 
> ```
> $ python io_tests/test_mrc_wrapper.py 
> ....
> ----------------------------------------------------------------------
> Ran 4 tests in 0.497s
> 
> OK
> ```
> 
> with:
> 
> ```
> $ python -c 'import mrcfile; print(mrcfile.version.__version__)'
> 1.3.0
> ```

The tests pass, so I am not sure what's confusing you here.

**Comment by constantinpape** [comment]
Can you please also add a test for 2d data?

**Comment by martinschorb** [comment]
So you just haven't merged it yet? I thought we got stuck with some errors in the tests. That was already too long ago and I was on holidays in between, so forgot about the details.
Then I will test the conversion for the 2D overview EM using my code and see how it looks...

**Comment by constantinpape** [comment]
> So you just haven't merged it yet? I thought we got stuck with some errors in the tests. That was already too long ago and I was on holidays in between, so forgot about the details.
> Then I will test the conversion for the 2D overview EM using my code and see how it looks...

I see. You're right. I also forgot about the details over that time. The tests are still failing in the CI...
I will check later if it works for me locally or not.

**Comment by constantinpape** [comment]
I can reproduce the test failures locally:
```
$ python test_mrc_wrapper.py 
FFFF
======================================================================
FAIL: test_dataset (__main__.TestMrcWrapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 49, in test_dataset
    self.check_dataset(ds)
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 43, in check_dataset
    self.assertTrue(np.array_equal(out, exp))
AssertionError: False is not true

======================================================================
FAIL: test_dataset_compressed (__main__.TestMrcWrapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 55, in test_dataset_compressed
    self.check_dataset(ds)
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 43, in check_dataset
    self.assertTrue(np.array_equal(out, exp))
AssertionError: False is not true

======================================================================
FAIL: test_file (__main__.TestMrcWrapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 61, in test_file
    self.check_dataset(ds)
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 43, in check_dataset
    self.assertTrue(np.array_equal(out, exp))
AssertionError: False is not true

======================================================================
FAIL: test_file_compressed (__main__.TestMrcWrapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 67, in test_file_compressed
    self.check_dataset(ds)
  File "/home/pape/Work/my_projects/elf/test/io_tests/test_mrc_wrapper.py", line 43, in check_dataset
    self.assertTrue(np.array_equal(out, exp))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 0.286s

FAILED (failures=4)
```

I also compared a few values quickly and they are very different, this is not just some rounding error.

And I have the same mrcfile version that you have: 
```
$ python -c "import mrcfile; print(mrcfile.__version__)"
1.3.0
```

**Comment by martinschorb** [comment]
confirm. Set up anew env and now it fails for me as well. Let me explore what's going on...

**Comment by martinschorb** [comment]
OK, I know what the problem is. Obviously the `mrcfile` writer handles the data the same as the reader. Therefore the axis order is consistent without the changes. But the order still needs to be swapped! So I changed that when generating the test data. Also it is working for both 2D and 3D data now with the new dimensionless code, so I think a 3D test should be sufficient.

**Comment by martinschorb** [comment]
so locally the tests run now for me:

```
$ python -c 'import mrcfile; print(mrcfile.version.__version__)'
1.3.0
$ python test_mrc_wrapper.py 
....
----------------------------------------------------------------------
Ran 4 tests in 0.686s

OK
```

**Review by constantinpape — APPROVED** [review]
The tests pass in the CI as well now. Thanks!

**Pull request merged**
